// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: messageToken.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//计算加法请求参数
type NumberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Arge1 int64 `protobuf:"varint,1,opt,name=Arge1,proto3" json:"Arge1,omitempty"`
	Arge2 int64 `protobuf:"varint,2,opt,name=Arge2,proto3" json:"Arge2,omitempty"`
}

func (x *NumberRequest) Reset() {
	*x = NumberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messageToken_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberRequest) ProtoMessage() {}

func (x *NumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messageToken_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberRequest.ProtoReflect.Descriptor instead.
func (*NumberRequest) Descriptor() ([]byte, []int) {
	return file_messageToken_proto_rawDescGZIP(), []int{0}
}

func (x *NumberRequest) GetArge1() int64 {
	if x != nil {
		return x.Arge1
	}
	return 0
}

func (x *NumberRequest) GetArge2() int64 {
	if x != nil {
		return x.Arge2
	}
	return 0
}

//订单信息
type AddInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int64 `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *AddInfo) Reset() {
	*x = AddInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messageToken_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddInfo) ProtoMessage() {}

func (x *AddInfo) ProtoReflect() protoreflect.Message {
	mi := &file_messageToken_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddInfo.ProtoReflect.Descriptor instead.
func (*AddInfo) Descriptor() ([]byte, []int) {
	return file_messageToken_proto_rawDescGZIP(), []int{1}
}

func (x *AddInfo) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_messageToken_proto protoreflect.FileDescriptor

var file_messageToken_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x22, 0x3b, 0x0a, 0x0d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x41, 0x72, 0x67, 0x65, 0x31, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x41, 0x72, 0x67, 0x65, 0x31, 0x12, 0x14, 0x0a, 0x05, 0x41, 0x72, 0x67,
	0x65, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x41, 0x72, 0x67, 0x65, 0x32, 0x22,
	0x21, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x32, 0x59, 0x0a, 0x0c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x49, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x73, 0x12, 0x1b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x2e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x2e,
	0x41, 0x64, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x04, 0x5a,
	0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messageToken_proto_rawDescOnce sync.Once
	file_messageToken_proto_rawDescData = file_messageToken_proto_rawDesc
)

func file_messageToken_proto_rawDescGZIP() []byte {
	file_messageToken_proto_rawDescOnce.Do(func() {
		file_messageToken_proto_rawDescData = protoimpl.X.CompressGZIP(file_messageToken_proto_rawDescData)
	})
	return file_messageToken_proto_rawDescData
}

var file_messageToken_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_messageToken_proto_goTypes = []interface{}{
	(*NumberRequest)(nil), // 0: messageToken.NumberRequest
	(*AddInfo)(nil),       // 1: messageToken.AddInfo
}
var file_messageToken_proto_depIdxs = []int32{
	0, // 0: messageToken.OrderService.GetOrderInfos:input_type -> messageToken.NumberRequest
	1, // 1: messageToken.OrderService.GetOrderInfos:output_type -> messageToken.AddInfo
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_messageToken_proto_init() }
func file_messageToken_proto_init() {
	if File_messageToken_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messageToken_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NumberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messageToken_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messageToken_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_messageToken_proto_goTypes,
		DependencyIndexes: file_messageToken_proto_depIdxs,
		MessageInfos:      file_messageToken_proto_msgTypes,
	}.Build()
	File_messageToken_proto = out.File
	file_messageToken_proto_rawDesc = nil
	file_messageToken_proto_goTypes = nil
	file_messageToken_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderServiceClient interface {
	GetOrderInfos(ctx context.Context, opts ...grpc.CallOption) (OrderService_GetOrderInfosClient, error)
}

type orderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderServiceClient(cc grpc.ClientConnInterface) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) GetOrderInfos(ctx context.Context, opts ...grpc.CallOption) (OrderService_GetOrderInfosClient, error) {
	stream, err := c.cc.NewStream(ctx, &_OrderService_serviceDesc.Streams[0], "/messageToken.OrderService/GetOrderInfos", opts...)
	if err != nil {
		return nil, err
	}
	x := &orderServiceGetOrderInfosClient{stream}
	return x, nil
}

type OrderService_GetOrderInfosClient interface {
	Send(*NumberRequest) error
	Recv() (*AddInfo, error)
	grpc.ClientStream
}

type orderServiceGetOrderInfosClient struct {
	grpc.ClientStream
}

func (x *orderServiceGetOrderInfosClient) Send(m *NumberRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *orderServiceGetOrderInfosClient) Recv() (*AddInfo, error) {
	m := new(AddInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// OrderServiceServer is the server API for OrderService service.
type OrderServiceServer interface {
	GetOrderInfos(OrderService_GetOrderInfosServer) error
}

// UnimplementedOrderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOrderServiceServer struct {
}

func (*UnimplementedOrderServiceServer) GetOrderInfos(OrderService_GetOrderInfosServer) error {
	return status.Errorf(codes.Unimplemented, "method GetOrderInfos not implemented")
}

func RegisterOrderServiceServer(s *grpc.Server, srv OrderServiceServer) {
	s.RegisterService(&_OrderService_serviceDesc, srv)
}

func _OrderService_GetOrderInfos_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OrderServiceServer).GetOrderInfos(&orderServiceGetOrderInfosServer{stream})
}

type OrderService_GetOrderInfosServer interface {
	Send(*AddInfo) error
	Recv() (*NumberRequest, error)
	grpc.ServerStream
}

type orderServiceGetOrderInfosServer struct {
	grpc.ServerStream
}

func (x *orderServiceGetOrderInfosServer) Send(m *AddInfo) error {
	return x.ServerStream.SendMsg(m)
}

func (x *orderServiceGetOrderInfosServer) Recv() (*NumberRequest, error) {
	m := new(NumberRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _OrderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "messageToken.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetOrderInfos",
			Handler:       _OrderService_GetOrderInfos_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "messageToken.proto",
}
