// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: messageToken.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//计算加法请求参数
type NumberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Arge1 int64 `protobuf:"varint,1,opt,name=Arge1,proto3" json:"Arge1,omitempty"`
	Arge2 int64 `protobuf:"varint,2,opt,name=Arge2,proto3" json:"Arge2,omitempty"`
}

func (x *NumberRequest) Reset() {
	*x = NumberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messageToken_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberRequest) ProtoMessage() {}

func (x *NumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messageToken_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberRequest.ProtoReflect.Descriptor instead.
func (*NumberRequest) Descriptor() ([]byte, []int) {
	return file_messageToken_proto_rawDescGZIP(), []int{0}
}

func (x *NumberRequest) GetArge1() int64 {
	if x != nil {
		return x.Arge1
	}
	return 0
}

func (x *NumberRequest) GetArge2() int64 {
	if x != nil {
		return x.Arge2
	}
	return 0
}

//订单信息
type AddInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int64 `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *AddInfo) Reset() {
	*x = AddInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messageToken_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddInfo) ProtoMessage() {}

func (x *AddInfo) ProtoReflect() protoreflect.Message {
	mi := &file_messageToken_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddInfo.ProtoReflect.Descriptor instead.
func (*AddInfo) Descriptor() ([]byte, []int) {
	return file_messageToken_proto_rawDescGZIP(), []int{1}
}

func (x *AddInfo) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_messageToken_proto protoreflect.FileDescriptor

var file_messageToken_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x22, 0x3b, 0x0a, 0x0d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x41, 0x72, 0x67, 0x65, 0x31, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x41, 0x72, 0x67, 0x65, 0x31, 0x12, 0x14, 0x0a, 0x05, 0x41, 0x72, 0x67,
	0x65, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x41, 0x72, 0x67, 0x65, 0x32, 0x22,
	0x21, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x32, 0x55, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x47, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x41, 0x64, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x12,
	0x1b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x41, 0x64, 0x64, 0x49,
	0x6e, 0x66, 0x6f, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messageToken_proto_rawDescOnce sync.Once
	file_messageToken_proto_rawDescData = file_messageToken_proto_rawDesc
)

func file_messageToken_proto_rawDescGZIP() []byte {
	file_messageToken_proto_rawDescOnce.Do(func() {
		file_messageToken_proto_rawDescData = protoimpl.X.CompressGZIP(file_messageToken_proto_rawDescData)
	})
	return file_messageToken_proto_rawDescData
}

var file_messageToken_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_messageToken_proto_goTypes = []interface{}{
	(*NumberRequest)(nil), // 0: messageToken.NumberRequest
	(*AddInfo)(nil),       // 1: messageToken.AddInfo
}
var file_messageToken_proto_depIdxs = []int32{
	0, // 0: messageToken.AddService.GetAddInfos:input_type -> messageToken.NumberRequest
	1, // 1: messageToken.AddService.GetAddInfos:output_type -> messageToken.AddInfo
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_messageToken_proto_init() }
func file_messageToken_proto_init() {
	if File_messageToken_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messageToken_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NumberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messageToken_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messageToken_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_messageToken_proto_goTypes,
		DependencyIndexes: file_messageToken_proto_depIdxs,
		MessageInfos:      file_messageToken_proto_msgTypes,
	}.Build()
	File_messageToken_proto = out.File
	file_messageToken_proto_rawDesc = nil
	file_messageToken_proto_goTypes = nil
	file_messageToken_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AddServiceClient is the client API for AddService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AddServiceClient interface {
	GetAddInfos(ctx context.Context, opts ...grpc.CallOption) (AddService_GetAddInfosClient, error)
}

type addServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAddServiceClient(cc grpc.ClientConnInterface) AddServiceClient {
	return &addServiceClient{cc}
}

func (c *addServiceClient) GetAddInfos(ctx context.Context, opts ...grpc.CallOption) (AddService_GetAddInfosClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AddService_serviceDesc.Streams[0], "/messageToken.AddService/GetAddInfos", opts...)
	if err != nil {
		return nil, err
	}
	x := &addServiceGetAddInfosClient{stream}
	return x, nil
}

type AddService_GetAddInfosClient interface {
	Send(*NumberRequest) error
	Recv() (*AddInfo, error)
	grpc.ClientStream
}

type addServiceGetAddInfosClient struct {
	grpc.ClientStream
}

func (x *addServiceGetAddInfosClient) Send(m *NumberRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *addServiceGetAddInfosClient) Recv() (*AddInfo, error) {
	m := new(AddInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AddServiceServer is the server API for AddService service.
type AddServiceServer interface {
	GetAddInfos(AddService_GetAddInfosServer) error
}

// UnimplementedAddServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAddServiceServer struct {
}

func (*UnimplementedAddServiceServer) GetAddInfos(AddService_GetAddInfosServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAddInfos not implemented")
}

func RegisterAddServiceServer(s *grpc.Server, srv AddServiceServer) {
	s.RegisterService(&_AddService_serviceDesc, srv)
}

func _AddService_GetAddInfos_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AddServiceServer).GetAddInfos(&addServiceGetAddInfosServer{stream})
}

type AddService_GetAddInfosServer interface {
	Send(*AddInfo) error
	Recv() (*NumberRequest, error)
	grpc.ServerStream
}

type addServiceGetAddInfosServer struct {
	grpc.ServerStream
}

func (x *addServiceGetAddInfosServer) Send(m *AddInfo) error {
	return x.ServerStream.SendMsg(m)
}

func (x *addServiceGetAddInfosServer) Recv() (*NumberRequest, error) {
	m := new(NumberRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _AddService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "messageToken.AddService",
	HandlerType: (*AddServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAddInfos",
			Handler:       _AddService_GetAddInfos_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "messageToken.proto",
}
